import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import localFont from '@next/font/local'

const organetto = localFont({
  src: [
    {
      path: '../../public/fonts/Fontspring-DEMO-organetto-bold.otf',
      weight: '600'
    },
    {
      path: '../../public/fonts/Fontspring-DEMO-organetto-semiextbold.otf',
      weight: '700'
    }
  ],
  variable: '--font-oragnetto'
})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Convera",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${organetto.variable} font-sans`}>
    {/*  <html lang="en"> */}
      <body className={inter.className}>

        <Navbar/>
        {children}</body>
    </html>
  );
}
